
version: '3.8'

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - order-db
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_order:/var/lib/postgresql/data

volumes:
  pgdata_order:
